const STORE_CONFIG = {
  storeName: "UrbanCart",
  whatsappNumber: "6281234567890",
  currency: "IDR",
  shippingCost: 20000,
  serviceFee: 3500,
  freeShippingMinimum: 500000,
  supportEmail: "hello@urbancart.local",
  supportPhone: "+62 812-3456-7890",
  address: "Jl. Sudirman No. 88, Jakarta Pusat",
};

const UC_CATEGORIES = ["Men", "Women", "Shoes", "Bags", "Accessories"];

const UC_PRODUCTS = [
  {
    id: 1,
    name: "Essential Oversized Tee",
    category: "Men",
    type: "T-Shirt",
    price: 129000,
    compareAt: 179000,
    rating: 4.8,
    reviews: 126,
    inStock: true,
    stock: 34,
    badge: "New",
    colors: ["Black", "White", "Olive"],
    sizes: ["S", "M", "L", "XL"],
    images: ["assets/images/product-tee.svg", "assets/images/product-tee-alt.svg", "assets/images/product-flatlay.svg"],
    description: "Kaos oversized berbahan cotton combed yang ringan, adem, dan mudah dipadukan untuk gaya harian.",
    details: ["Cotton combed 24s", "Cutting oversized", "Sablon halus tahan cuci", "Made in Indonesia"],
    createdAt: "2026-07-04",
    sold: 421,
    sku: "URB-MEN-TEE-001",
  },
  {
    id: 2,
    name: "Luna Relaxed Shirt",
    category: "Women",
    type: "Shirt",
    price: 189000,
    compareAt: 239000,
    rating: 4.7,
    reviews: 91,
    inStock: true,
    stock: 18,
    badge: "Sale",
    colors: ["White", "Sky", "Beige"],
    sizes: ["S", "M", "L"],
    images: ["assets/images/product-shirt.svg", "assets/images/product-flatlay.svg", "assets/images/product-tee-alt.svg"],
    description: "Kemeja relaxed dengan tekstur lembut untuk tampilan smart casual yang tetap nyaman.",
    details: ["Rayon blend", "Kancing depan", "Manset lengan", "Regular length"],
    createdAt: "2026-06-28",
    sold: 288,
    sku: "URB-WMN-SHT-002",
  },
  {
    id: 3,
    name: "Metro Runner Sneakers",
    category: "Shoes",
    type: "Sneakers",
    price: 399000,
    compareAt: 529000,
    rating: 4.9,
    reviews: 174,
    inStock: true,
    stock: 22,
    badge: "Best Seller",
    colors: ["White", "Black", "Grey"],
    sizes: ["39", "40", "41", "42", "43"],
    images: ["assets/images/product-sneaker.svg", "assets/images/product-shoes.svg", "assets/images/product-flatlay.svg"],
    description: "Sneakers ringan dengan outsole empuk untuk aktivitas kota, kampus, dan weekend trip.",
    details: ["Upper synthetic leather", "Outsole EVA", "Insole breathable", "Unisex fit"],
    createdAt: "2026-06-20",
    sold: 732,
    sku: "URB-SHO-SNK-003",
  },
  {
    id: 4,
    name: "Avenue Mini Sling Bag",
    category: "Bags",
    type: "Sling Bag",
    price: 219000,
    compareAt: null,
    rating: 4.6,
    reviews: 58,
    inStock: true,
    stock: 25,
    badge: "New",
    colors: ["Black", "Tan", "Navy"],
    sizes: ["One Size"],
    images: ["assets/images/product-bag.svg", "assets/images/product-flatlay.svg", "assets/images/product-watch.svg"],
    description: "Tas selempang compact dengan kompartemen rapi untuk ponsel, dompet, dan kebutuhan harian.",
    details: ["Water repellent", "Adjustable strap", "2 inner pockets", "Magnetic flap"],
    createdAt: "2026-07-01",
    sold: 201,
    sku: "URB-BAG-SLG-004",
  },
  {
    id: 5,
    name: "Chrono Field Watch",
    category: "Accessories",
    type: "Watch",
    price: 349000,
    compareAt: 429000,
    rating: 4.8,
    reviews: 103,
    inStock: true,
    stock: 15,
    badge: "Sale",
    colors: ["Black", "Silver", "Brown"],
    sizes: ["One Size"],
    images: ["assets/images/product-watch.svg", "assets/images/product-flatlay.svg", "assets/images/product-bag.svg"],
    description: "Jam tangan analog minimalis dengan strap nyaman dan tampilan bersih untuk berbagai outfit.",
    details: ["Quartz movement", "Stainless case", "Leather strap", "Water resistant 3 ATM"],
    createdAt: "2026-06-16",
    sold: 360,
    sku: "URB-ACC-WAT-005",
  },
  {
    id: 6,
    name: "Urban Cargo Pants",
    category: "Men",
    type: "Pants",
    price: 279000,
    compareAt: null,
    rating: 4.5,
    reviews: 67,
    inStock: true,
    stock: 19,
    badge: "Best Seller",
    colors: ["Olive", "Black", "Khaki"],
    sizes: ["28", "30", "32", "34", "36"],
    images: ["assets/images/product-pants.svg", "assets/images/product-flatlay.svg", "assets/images/product-jacket.svg"],
    description: "Cargo pants dengan banyak kantong, cutting straight, dan bahan twill yang kuat.",
    details: ["Cotton twill", "Elastic side waist", "Six pockets", "Straight fit"],
    createdAt: "2026-05-30",
    sold: 548,
    sku: "URB-MEN-PNT-006",
  },
  {
    id: 7,
    name: "Serene Knit Cardigan",
    category: "Women",
    type: "Jacket",
    price: 259000,
    compareAt: 319000,
    rating: 4.7,
    reviews: 84,
    inStock: true,
    stock: 12,
    badge: "New",
    colors: ["Cream", "Charcoal", "Mauve"],
    sizes: ["S", "M", "L", "XL"],
    images: ["assets/images/product-jacket.svg", "assets/images/product-shirt.svg", "assets/images/product-flatlay.svg"],
    description: "Cardigan rajut lembut dengan siluet clean untuk layering kantor maupun santai.",
    details: ["Soft knit", "Drop shoulder", "Front button", "Ribbed hem"],
    createdAt: "2026-07-03",
    sold: 167,
    sku: "URB-WMN-JKT-007",
  },
  {
    id: 8,
    name: "Commuter Backpack 18L",
    category: "Bags",
    type: "Backpack",
    price: 329000,
    compareAt: 399000,
    rating: 4.9,
    reviews: 149,
    inStock: true,
    stock: 20,
    badge: "Best Seller",
    colors: ["Black", "Grey", "Navy"],
    sizes: ["18L"],
    images: ["assets/images/product-backpack.svg", "assets/images/product-bag.svg", "assets/images/product-flatlay.svg"],
    description: "Backpack modern untuk laptop 14 inci, kompartemen rapi, dan material tahan percikan air.",
    details: ["Laptop sleeve", "Hidden back pocket", "Padded strap", "Water repellent"],
    createdAt: "2026-06-11",
    sold: 612,
    sku: "URB-BAG-BPK-008",
  },
  {
    id: 9,
    name: "Classic Denim Jacket",
    category: "Men",
    type: "Jacket",
    price: 359000,
    compareAt: 459000,
    rating: 4.6,
    reviews: 73,
    inStock: true,
    stock: 14,
    badge: "Sale",
    colors: ["Blue", "Black"],
    sizes: ["M", "L", "XL"],
    images: ["assets/images/product-jacket.svg", "assets/images/product-pants.svg", "assets/images/product-flatlay.svg"],
    description: "Jaket denim klasik dengan wash natural dan konstruksi kokoh untuk tampilan timeless.",
    details: ["12 oz denim", "Metal button", "Chest pockets", "Regular fit"],
    createdAt: "2026-05-24",
    sold: 338,
    sku: "URB-MEN-JKT-009",
  },
  {
    id: 10,
    name: "Nova Platform Sneakers",
    category: "Shoes",
    type: "Sneakers",
    price: 429000,
    compareAt: null,
    rating: 4.8,
    reviews: 112,
    inStock: true,
    stock: 10,
    badge: "New",
    colors: ["White", "Pink", "Black"],
    sizes: ["36", "37", "38", "39", "40"],
    images: ["assets/images/product-shoes.svg", "assets/images/product-sneaker.svg", "assets/images/product-flatlay.svg"],
    description: "Sneakers platform dengan bentuk clean, nyaman dipakai lama, dan cocok untuk daily outfit.",
    details: ["Platform sole", "Cushioned footbed", "Lace-up closure", "Women fit"],
    createdAt: "2026-07-05",
    sold: 229,
    sku: "URB-SHO-PLT-010",
  },
  {
    id: 11,
    name: "Everyday Rib Tank",
    category: "Women",
    type: "T-Shirt",
    price: 99000,
    compareAt: 139000,
    rating: 4.4,
    reviews: 42,
    inStock: true,
    stock: 27,
    badge: "Sale",
    colors: ["White", "Black", "Sage"],
    sizes: ["S", "M", "L"],
    images: ["assets/images/product-tee-alt.svg", "assets/images/product-shirt.svg", "assets/images/product-flatlay.svg"],
    description: "Tank top rib yang elastis dan breathable, ideal sebagai inner atau outfit musim panas.",
    details: ["Rib cotton", "Stretch fabric", "Slim fit", "Soft handfeel"],
    createdAt: "2026-06-05",
    sold: 192,
    sku: "URB-WMN-TEE-011",
  },
  {
    id: 12,
    name: "Minimal Leather Belt",
    category: "Accessories",
    type: "Accessories",
    price: 149000,
    compareAt: null,
    rating: 4.5,
    reviews: 36,
    inStock: true,
    stock: 30,
    badge: "New",
    colors: ["Black", "Brown"],
    sizes: ["S", "M", "L"],
    images: ["assets/images/product-accessory.svg", "assets/images/product-watch.svg", "assets/images/product-flatlay.svg"],
    description: "Ikat pinggang minimalis dengan buckle matte untuk melengkapi tampilan kasual dan formal.",
    details: ["Synthetic leather", "Matte buckle", "Adjustable holes", "Gift box included"],
    createdAt: "2026-07-02",
    sold: 88,
    sku: "URB-ACC-BLT-012",
  },
  {
    id: 13,
    name: "Daily Oxford Shirt",
    category: "Men",
    type: "Shirt",
    price: 219000,
    compareAt: 269000,
    rating: 4.7,
    reviews: 64,
    inStock: true,
    stock: 16,
    badge: "Best Seller",
    colors: ["White", "Blue", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    images: ["assets/images/product-shirt.svg", "assets/images/product-tee.svg", "assets/images/product-flatlay.svg"],
    description: "Kemeja oxford harian dengan struktur rapi dan bahan yang tetap nyaman untuk cuaca tropis.",
    details: ["Oxford cotton", "Button down collar", "Regular fit", "Curved hem"],
    createdAt: "2026-05-18",
    sold: 407,
    sku: "URB-MEN-SHT-013",
  },
  {
    id: 14,
    name: "Softline Wide Pants",
    category: "Women",
    type: "Pants",
    price: 239000,
    compareAt: 299000,
    rating: 4.6,
    reviews: 79,
    inStock: true,
    stock: 9,
    badge: "Sale",
    colors: ["Black", "Cream", "Mocha"],
    sizes: ["S", "M", "L", "XL"],
    images: ["assets/images/product-pants.svg", "assets/images/product-shirt.svg", "assets/images/product-flatlay.svg"],
    description: "Celana wide leg dengan drape lembut yang nyaman untuk kerja, kuliah, dan hangout.",
    details: ["Poly rayon", "Side zipper", "Wide leg", "High waist"],
    createdAt: "2026-06-22",
    sold: 251,
    sku: "URB-WMN-PNT-014",
  },
  {
    id: 15,
    name: "Trail Low Sneakers",
    category: "Shoes",
    type: "Sneakers",
    price: 459000,
    compareAt: 579000,
    rating: 4.7,
    reviews: 98,
    inStock: false,
    stock: 0,
    badge: "Sale",
    colors: ["Black", "Olive", "Sand"],
    sizes: ["40", "41", "42", "43", "44"],
    images: ["assets/images/product-sneaker.svg", "assets/images/product-shoes.svg", "assets/images/product-flatlay.svg"],
    description: "Sneakers bergaya trail dengan grip kuat dan siluet rendah untuk aktivitas outdoor ringan.",
    details: ["Rubber outsole", "Mesh upper", "Pull tab", "Padded collar"],
    createdAt: "2026-05-12",
    sold: 343,
    sku: "URB-SHO-TRL-015",
  },
  {
    id: 16,
    name: "Studio Tote Bag",
    category: "Bags",
    type: "Tote Bag",
    price: 179000,
    compareAt: 219000,
    rating: 4.5,
    reviews: 55,
    inStock: true,
    stock: 24,
    badge: "New",
    colors: ["Canvas", "Black", "Sage"],
    sizes: ["One Size"],
    images: ["assets/images/product-bag.svg", "assets/images/product-backpack.svg", "assets/images/product-flatlay.svg"],
    description: "Tote bag tebal dengan zipper atas dan ruang luas untuk laptop, buku, serta barang belanja.",
    details: ["Heavy canvas", "Top zipper", "Inner pocket", "Long handle"],
    createdAt: "2026-07-06",
    sold: 119,
    sku: "URB-BAG-TOT-016",
  },
  {
    id: 17,
    name: "Arc Hoodie",
    category: "Men",
    type: "Hoodie",
    price: 299000,
    compareAt: 379000,
    rating: 4.8,
    reviews: 137,
    inStock: true,
    stock: 11,
    badge: "Best Seller",
    colors: ["Black", "Grey", "Maroon"],
    sizes: ["M", "L", "XL"],
    images: ["assets/images/product-jacket.svg", "assets/images/product-tee.svg", "assets/images/product-flatlay.svg"],
    description: "Hoodie fleece tebal dengan fit santai, kantong depan, dan detail logo minimal.",
    details: ["Cotton fleece", "Kangaroo pocket", "Drawstring hood", "Rib cuff"],
    createdAt: "2026-06-02",
    sold: 690,
    sku: "URB-MEN-HOD-017",
  },
  {
    id: 18,
    name: "Pearl Hoop Earrings",
    category: "Accessories",
    type: "Accessories",
    price: 89000,
    compareAt: 119000,
    rating: 4.3,
    reviews: 31,
    inStock: true,
    stock: 42,
    badge: "Sale",
    colors: ["Gold", "Silver"],
    sizes: ["One Size"],
    images: ["assets/images/product-accessory.svg", "assets/images/product-watch.svg", "assets/images/product-flatlay.svg"],
    description: "Anting hoop mungil dengan aksen pearl yang memberi sentuhan elegan tanpa berlebihan.",
    details: ["Alloy plated", "Lightweight", "Nickel safe", "Velvet pouch"],
    createdAt: "2026-06-14",
    sold: 158,
    sku: "URB-ACC-ERN-018",
  },
  {
    id: 19,
    name: "City Linen Blazer",
    category: "Women",
    type: "Jacket",
    price: 389000,
    compareAt: 489000,
    rating: 4.9,
    reviews: 121,
    inStock: true,
    stock: 8,
    badge: "Best Seller",
    colors: ["Ivory", "Black", "Sage"],
    sizes: ["S", "M", "L"],
    images: ["assets/images/product-jacket.svg", "assets/images/product-shirt.svg", "assets/images/product-flatlay.svg"],
    description: "Blazer linen blend yang ringan dan berstruktur, cocok untuk tampilan profesional yang modern.",
    details: ["Linen blend", "Single button", "Half lining", "Relaxed fit"],
    createdAt: "2026-06-26",
    sold: 375,
    sku: "URB-WMN-BLZ-019",
  },
  {
    id: 20,
    name: "Core Baseball Cap",
    category: "Accessories",
    type: "Accessories",
    price: 109000,
    compareAt: null,
    rating: 4.4,
    reviews: 44,
    inStock: true,
    stock: 38,
    badge: "New",
    colors: ["Black", "Navy", "Khaki"],
    sizes: ["One Size"],
    images: ["assets/images/product-accessory.svg", "assets/images/product-flatlay.svg", "assets/images/product-tee.svg"],
    description: "Topi baseball basic dengan strap adjustable dan panel depan kokoh untuk gaya kasual.",
    details: ["Cotton twill", "Adjustable strap", "Embroidered mark", "Curved brim"],
    createdAt: "2026-07-07",
    sold: 96,
    sku: "URB-ACC-CAP-020",
  },
];

window.STORE_CONFIG = STORE_CONFIG;
window.UC_CATEGORIES = UC_CATEGORIES;
window.UC_PRODUCTS = UC_PRODUCTS;
